# Generated by Django 2.0 on 2018-01-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='getimage',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
